### ISSUE TITLE
[Bug] A group device disapars after Homebridge restart

### ISSUE THREAD

**Issue by arturdobo** [itavero/homebridge-z2m#503]
I created the device group in ZIgbee2MQTT using the following config:

```
  '1':
    friendly_name: livingroom_wall_light_with_dimmer
    optimistic: false
    devices:
      - 0x00124b002114dfc9/11 -> dimmer
      - 0x60a423fffe94f55a/1 -> switch
```
The new device appeared in my Homekit dashboard. I was able to control it, I mean, changing brightness, turning it on and off. Unfortunately, after Homebridge restart, the device is gone. If I remove one of the devices from the group and add it once again, the device reappears on my Homekit dashboard, but as before, till the next Homebridge restart. 

I suspect maybe something is wrong because those two devices expose different properties. I mean the dimmer exposes "state" and "brightness" while the switch "state" only. When I create a group of two of the same devices i.e. switches, they survive restarts.

Homebridge version: v1.5.0
Plugin version: homebridge-z2m v1.9.0 
Zigbee2MQTT 1.27.0
