### ISSUE TITLE
[CI] save-state and set-output commands are deprecated

### ISSUE THREAD

**Issue by itavero** [itavero/homebridge-z2m#570]
GitHub has [deprecated the use of save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

The workflow should be updated from this:
```yml
- name: Save state
  run: echo "::save-state name={name}::{value}"

- name: Set output
  run: echo "::set-output name={name}::{value}"
```

To this, writing to the new `GITHUB_STATE` and `GITHUB_OUTPUT` environment files:
```yml
- name: Save state
  run: echo "{name}={value}" >> $GITHUB_STATE

- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```
